### ISSUE TITLE
`attribute` `default` option doesn't work with `:&`

### ISSUE THREAD

**Issue by hangsu** [joeldrapper/literal#82]
This doesn't work:

```ruby
class Procy
 extend Literal::Attributes
 attribute :some_proc, Proc, :&, default: -> { proc {} }
end
```

```
irb(main):016> Procy.new
/ruby/gems/3.2.0/bundler/gems/literal-455f225574db/lib/literal/attributable.rb:81:in `initialize': Expected `nil` to be of type: `Proc`. (Literal::TypeError)
```

**Comment by joeldrapper** [comment]
The reason this doesn't currently work is because you can’t assign a default block in Ruby arguments. We will need to fix this by generating some code in the body that checks for nil block arguments and assigns them to their default value.

Positional and keyword splats are also broken and can’t be fixed because they default to an empty array or empty hash, and we can’t detect if this empty array or empty hash was intentionally passed or a default fallback.

For these, we should raise an error at property definition.

**Comment by hangsu** [comment]
Thanks for the fix!

> For these, we should raise an error at property definition.

Makes sense to me. Missing features/behavior in `literal` is usually easy to work around (esp with `after_initialize`), so it doesn't bother me. But having eager and helpful errors is really where the value of `literal` lies, so I appreciate leaning into that.
